# Generated by Django 4.1.3 on 2022-12-10 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 6, 23, 25, 175753), verbose_name='Время жизни'),
        ),
    ]
