# Generated by Django 4.1.3 on 2022-12-10 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_life_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 6, 24, 5, 346358), verbose_name='Время жизни'),
        ),
    ]
