# Generated by Django 4.1.3 on 2022-12-20 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_question_life_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='life_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 9, 1, 44, 493556), verbose_name='Время жизни'),
        ),
    ]
